WebApp/Controllers/CategoryController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using FinTrack.Models;
using FinTrack.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

[Authorize]
public class CategoryController : Controller
{
    private readonly ILogger<CategoryController> _logger;
    private readonly ICategoryService _categoryService;

    public CategoryController(ILogger<CategoryController> logger, ICategoryService categoryService)
    {
        _logger = logger;
        _categoryService = categoryService;
    }

    public async Task<IActionResult> Index()
    {
        var categories = await _categoryService.FindAll();
        return View(categories);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category category)
    {
        if (!ModelState.IsValid)
        {
            return View(category);
        }

        try
        {
            await _categoryService.Create(category);
        }
        catch (Exception e)
        {
            ModelState.AddModelError("", e.Message);
            return View(category);
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Update(int? id)
    {
        if (id == null)
        {
            return BadRequest("ID not specified");
        }

        var category = await _categoryService.Find((int)id);
        if (category == null)
        {
            return NotFound("Category not found");
        }

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(Category category)
    {
        if (!ModelState.IsValid)
        {
            return View(category);
        }

        try
        {
            await _categoryService.Update(category);
        }
        catch (Exception e)
        {
            ModelState.AddModelError("", e.Message);
            return View(category);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return BadRequest("ID not specified");
        }

        try
        {
            await _categoryService.Delete((int)id);
        }
        catch (Exception e)
        {
            return BadRequest(e.Message);
        }

        return RedirectToAction("Index");
    }
}

WebApp/Controllers/TransactionController.cs
using FinTrack.Models;
using FinTrack.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FinTrack.Models.ViewModels;
using System.Security.Claims;

namespace WebApp.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ILogger<TransactionController> _logger;
        private readonly ITransactionService _transactionService;
        private readonly ICategoryService _categoryService;

        public TransactionController(
            ILogger<TransactionController> logger,
            ITransactionService transactionService,
            ICategoryService categoryService)
        {
            _logger = logger;
            _transactionService = transactionService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(TransactionSearchViewModel searchModel)
        {
            var allCategories = await _categoryService.FindAll();
            ViewBag.AllCategories = new SelectList(allCategories, "Id", "Name");
            ViewBag.TaxTypes = new SelectList(Enum.GetNames(typeof(TaxType)));

            var transactions = await _transactionService.Search(searchModel);

            searchModel.Transactions = transactions;
            return View(searchModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = new SelectList(await _categoryService.FindAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Transaction transaction)
        {
            ViewBag.Categories = new SelectList(await _categoryService.FindAll(), "Id", "Name", transaction.CategoryId);
            transaction.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            // if (!ModelState.IsValid)
            //     return View(transaction);

            try
            {
                await _transactionService.Create(transaction);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(transaction);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return BadRequest("ID not specified");

            var transaction = await _transactionService.Find((int)id);
            if (transaction == null)
                return NotFound("Transaction not found");

            ViewBag.Categories = new SelectList(await _categoryService.FindAll(), "Id", "Name", transaction.CategoryId);

            return View(transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Transaction transaction)
        {
            ViewBag.Categories = new SelectList(await _categoryService.FindAll(), "Id", "Name", transaction.CategoryId);

            if (!ModelState.IsValid)
                return View(transaction);

            try
            {
                await _transactionService.Update(transaction);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(transaction);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _transactionService.Delete(id);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>

<body>
    <header class="header-class">
        <nav
            class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow custom-navbar-bg">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">FinTrack</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Category"
                                asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Transaction"
                                asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account"
                                asp-action="Profile">Profile</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- 🔹 React + ReactDOM + Babel -->
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>